pipeline:
  validate:
    image: quay.io/ukhomeofficedigital/acp-toolset:v0.0.11
    pull: true
    commands:
    - if [ ! -z "$(terraform fmt)" ]; then echo "the above files have formatting error, please run a 'terraform fmt'"; fi
    - if [ ! -z "$(terraform validate -check-variables=false)" ]; then echo "the above files have formatting error, please run a 'terraform fmt'"; fi
    when:
      event: pull_request
